Linear Equation

In [ ]:
# y = 2 X1 + 3 X2 + 5

""" 
y is dependent variable
X1 and X2 are independent variables
5 is the intercept or the bias term
"""
# If x is powered by > 1 then its not linear equation
# all x is features, and y is target
# All x's are called X = [x1, x2, x3,...xn] (capital X is victor of features)




In [1]:
pip install numpy

  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/d4/b5/94c1e79fcbab38d1ca15e13777477b2914dd2d559b410f96949d6637b085/numpy-2.4.0-cp312-cp312-win_amd64.whl.metadata
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB 667.8 kB/s eta 0:00:19
   ---------------------------------------- 0.1/12.3 MB 1.1 MB/s eta 0:00:12
    --------------------------------------- 0.2/12.3 MB 1.2 MB/s eta 0:00:11
    --------------------------------------- 0.3/12.3 MB 1.3 MB/s eta 0:00:10
   - -------------------------------------- 0.3/12.3 MB 1.3 MB/s eta 0:00:10
   - -------------------------------------- 0.4/12.3 MB 1.4 MB/s eta 0:00:09
   - -------------------------------------- 0.5/12.3 MB 1.4 MB/s eta 0:00:09
   - -------------------------------------- 0.6/12.3 MB 1.4 MB/s eta 0:00:09
   - ---------------------------------


[notice] A new release of pip is available: 23.2.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import numpy as np

Numpy Arrays

In [5]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
print(v1) 
print(type(v1))
v1 + v2 
print(v1.dot(v2))  # dot product

[1 2 3]
<class 'numpy.ndarray'>
32


Matrix 

In [ ]:
m1 = np.array([[1, 2, 3], 
               [4, 5, 6], 
               [7, 8, 9]])

print(m1.shape) 
print(m1.ndim) 




(3, 3)
2


Reshaping 

In [10]:
vec = np.array([1, 2, 3, 4, 5, 6])
mat = vec.reshape(3,2)
mat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
vec = np.array([1, 2, 3, 4])
vec.shape[0]

4

In [12]:
mat = vec.reshape((vec.shape[0], 1))
mat

array([[1],
       [2],
       [3],
       [4]])

In [14]:
mat = np.array([[1.1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
mat.dtype

dtype('float64')

Data Types Priorities 

In [17]:
# object , string , float, int , bool

In [15]:
class C:
    x = 3
c1 = C()

In [ ]:
mat = np.array([[c1,8],
                 [3,2]])
mat.dtype

# it see it as object as it came from class
# thats why the dataset are seen as object dtype, they come from csv or excel files

dtype('O')

In [21]:
mat = np.array([[1, 2, 3],
                [4, "5", 6],
                [7, 8, 9]])

float_mat = mat.astype(float)
float_mat

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

Indexing

In [22]:
v = np.array([1, 2, 3, 4, 5])
v[2:5]

array([3, 4, 5])